---
title: "Police Research"
author: "Sony Suo"
fontsize: 12pt
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
```{r getting data, echo=FALSE}
library(tidyverse)
library(lubridate)
library(ggthemes)
library(scales)
police <- read.csv('https://goo.gl/nNAuDy')
```

## Police incidences table

```{r, echo = FALSE, warning=FALSE, message=FALSE, results = 'asis'}
library(knitr)
police %>% group_by(event_clearance_subgroup) %>% summarise(n = n()) %>% kable(format = 'markdown')
```
This is a table showing that the descriptive statistics of the amount and type of the police cases.


## Police incidences chart

```{r plot, echo=FALSE, fig.align='center'}
police %>% 
  filter(district_sector %in% c('B', 'E', 'D', 'R', 'O', 'C', 'K') & event_clearance_group %in% c('TRAFFIC RELATED CALLS', 'FRAUD CALLS', 'BURGLARY', 'BIKE')) %>%
  ggplot(aes(district_sector, fill = event_clearance_group)) + geom_bar() +
  labs(x = 'District Sector'
       , y = 'Incidences by Event\nClearance Group (#)'
       , fill = element_blank()
       , title = 'Incendences'
       , subtitle = 'By district sector')+
  theme_hc(bgcolor = "darkunica")+
  scale_fill_pander()
```

## Thank you for teaching us R!
